openapi: 3.0.0
info:
  title: новый api
  version: 1.0.0
  description: ''
servers:
  - url: /postman
  - url: ''
paths:
  /comments:
    get:
      summary: comment Service List
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        authorId:
                          type: integer
                        postId:
                          type: integer
                        body:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - authorId
                        - postId
                        - body
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - comments
                  - total
                  - skip
                  - limit
              example:
                comments:
                  - id: 3213
                    authorId: 7416
                    postId: 7536
                    body: string
                  - id: 5929
                    authorId: 5363
                    postId: 8014
                    body: str
                total: 8709
                skip: 5940
                limit: 30
      tags:
        - comments
    post:
      summary: comment Service Create
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  authorId:
                    type: integer
                  postId:
                    type: integer
                  body:
                    type: string
                    minLength: 1
                required:
                  - id
                  - authorId
                  - postId
                  - body
              example:
                id: 2844
                authorId: 7939
                postId: 8231
                body: string
      tags:
        - comments
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: integer
                body:
                  type: string
                  minLength: 1
              required:
                - postId
                - body
            example:
              postId: 6265
              body: string
  '/comments/{id}':
    get:
      summary: comment Service Get
      parameters:
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  authorId:
                    type: integer
                  postId:
                    type: integer
                  body:
                    type: string
                    minLength: 1
                required:
                  - id
                  - authorId
                  - postId
                  - body
              example:
                id: 2844
                authorId: 7939
                postId: 8231
                body: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - comments
        - '{id}'
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: string
    patch:
      summary: comment Service Update
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  authorId:
                    type: integer
                  postId:
                    type: integer
                  body:
                    type: string
                    minLength: 1
                required:
                  - id
                  - authorId
                  - postId
                  - body
              example:
                id: 2844
                authorId: 7939
                postId: 8231
                body: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - comments
        - '{id}'
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: integer
                body:
                  type: string
                  minLength: 1
            example:
              postId: 5052
              body: string
    delete:
      summary: comment Service Delete
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful.'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - comments
        - '{id}'
      security:
        - BearerAuth: []
  /courses:
    get:
      summary: course Service List
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          schema:
            type: string
          example: 'string,string'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  courses:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                          minLength: 1
                        description:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - title
                        - description
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - courses
                  - total
                  - skip
                  - limit
              example:
                courses:
                  - id: 263
                    title: string
                    description: string
                  - id: 7568
                    title: string
                    description: string
                total: 6410
                skip: 0
                limit: 30
      tags:
        - courses
      security:
        - ApiKeyAuth: []
    post:
      summary: course Service Create
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                required:
                  - id
                  - title
                  - description
              example:
                id: 1085
                title: string
                description: string
      tags:
        - courses
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
              required:
                - title
                - description
            example:
              title: string
              description: string
  '/courses/{id}':
    get:
      summary: course Service Get
      parameters:
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                required:
                  - id
                  - title
                  - description
              example:
                id: 1085
                title: string
                description: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - courses
        - '{id}'
      security:
        - ApiKeyAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: string
    patch:
      summary: course Service Update
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                required:
                  - id
                  - title
                  - description
              example:
                id: 1085
                title: string
                description: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - courses
        - '{id}'
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
            example:
              title: string
              description: string
    delete:
      summary: course Service Delete
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful.'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - courses
        - '{id}'
      security:
        - ApiKeyAuth: []
  /login:
    post:
      summary: auth Service Create
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    minLength: 1
                required:
                  - token
              example:
                token: string
      tags:
        - login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 1
              required:
                - email
                - password
            example:
              email: string
              password: string
  /posts:
    get:
      summary: post Service List
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        authorId:
                          type: integer
                        title:
                          type: string
                          minLength: 1
                        body:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - authorId
                        - title
                        - body
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - posts
                  - total
                  - skip
                  - limit
              example:
                posts:
                  - id: 900
                    authorId: 57
                    title: string
                    body: string
                  - id: 7337
                    authorId: 6165
                    title: string
                    body: string
                total: 558
                skip: 9145
                limit: 30
      tags:
        - posts
    post:
      summary: post Service Create
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  authorId:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  body:
                    type: string
                    minLength: 1
                required:
                  - id
                  - authorId
                  - title
                  - body
              example:
                id: 4893
                authorId: 6087
                title: string
                body: string
      tags:
        - posts
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                body:
                  type: string
                  minLength: 1
              required:
                - title
                - body
            example:
              title: string
              body: string
  '/posts/{id}':
    get:
      summary: post Service Get
      parameters:
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  authorId:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  body:
                    type: string
                    minLength: 1
                required:
                  - id
                  - authorId
                  - title
                  - body
              example:
                id: 4893
                authorId: 6087
                title: string
                body: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - posts
        - '{id}'
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: string
    patch:
      summary: post Service Update
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  authorId:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  body:
                    type: string
                    minLength: 1
                required:
                  - id
                  - authorId
                  - title
                  - body
              example:
                id: 4893
                authorId: 6087
                title: string
                body: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - posts
        - '{id}'
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                body:
                  type: string
                  minLength: 1
            example:
              title: string
              body: string
    delete:
      summary: post Service Delete
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful.'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - posts
        - '{id}'
      security:
        - BearerAuth: []
  '/posts/{postId}/comments':
    get:
      summary: post Service Get Comments
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        authorId:
                          type: integer
                        postId:
                          type: integer
                        body:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - authorId
                        - postId
                        - body
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - comments
                  - total
                  - skip
                  - limit
              example:
                comments:
                  - id: 3213
                    authorId: 7416
                    postId: 7536
                    body: string
                  - id: 5929
                    authorId: 5363
                    postId: 8014
                    body: str
                total: 8709
                skip: 5940
                limit: 30
      tags:
        - posts
        - '{postId}'
        - comments
    parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: string
        example: string
  /tasks:
    get:
      summary: task Service List
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          schema:
            type: string
          example: 'string,string'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                          minLength: 1
                        description:
                          type: string
                          minLength: 1
                        status:
                          type: string
                          enum:
                            - Backlog
                            - Ready
                            - In Progress
                            - Done
                            - Archived
                      required:
                        - id
                        - title
                        - description
                        - status
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - tasks
                  - total
                  - skip
                  - limit
              example:
                tasks:
                  - id: 3738
                    title: string
                    description: string
                    status: Backlog
                  - id: 1615
                    title: string
                    description: string
                    status: Done
                total: 2679
                skip: 0
                limit: 30
      tags:
        - tasks
    post:
      summary: task Service Create
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                  status:
                    type: string
                    enum:
                      - Backlog
                      - Ready
                      - In Progress
                      - Done
                      - Archived
                required:
                  - id
                  - title
                  - description
                  - status
              example:
                id: 7950
                title: string
                description: string
                status: Backlog
      tags:
        - tasks
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
                status:
                  allOf:
                    - type: string
              required:
                - title
                - description
            example:
              title: string
              description: string
              status: Done
  '/tasks/{id}':
    get:
      summary: task Service Get
      parameters:
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                  status:
                    type: string
                    enum:
                      - Backlog
                      - Ready
                      - In Progress
                      - Done
                      - Archived
                required:
                  - id
                  - title
                  - description
                  - status
              example:
                id: 7950
                title: string
                description: string
                status: Backlog
        '404':
          description: The server cannot find the requested resource.
      tags:
        - tasks
        - '{id}'
      security:
        - BasicAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: string
    patch:
      summary: task Service Update
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                  status:
                    type: string
                    enum:
                      - Backlog
                      - Ready
                      - In Progress
                      - Done
                      - Archived
                required:
                  - id
                  - title
                  - description
                  - status
              example:
                id: 7950
                title: string
                description: string
                status: Backlog
        '404':
          description: The server cannot find the requested resource.
      tags:
        - tasks
        - '{id}'
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
                status:
                  type: string
                  enum:
                    - Backlog
                    - Ready
                    - In Progress
                    - Done
                    - Archived
            example:
              title: string
              description: string
              status: Archived
    delete:
      summary: task Service Delete
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful.'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - tasks
        - '{id}'
      security:
        - BasicAuth: []
  /users:
    get:
      summary: user Service List
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          schema:
            type: string
          example: 'string,string'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
                          minLength: 1
                        firstName:
                          type: string
                          minLength: 1
                        lastName:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - email
                        - firstName
                        - lastName
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - users
                  - total
                  - skip
                  - limit
              example:
                users:
                  - id: 4819
                    email: string
                    firstName: string
                    lastName: string
                  - id: 603
                    email: string
                    firstName: string
                    lastName: string
                total: 1173
                skip: 0
                limit: 30
      tags:
        - users
    post:
      summary: user Service Create
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                    minLength: 1
                  firstName:
                    type: string
                    minLength: 1
                  lastName:
                    type: string
                    minLength: 1
                required:
                  - id
                  - email
                  - firstName
                  - lastName
              example:
                id: 2611
                email: string
                firstName: string
                lastName: string
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 1
              required:
                - email
                - firstName
                - lastName
                - password
            example:
              email: string
              firstName: string
              lastName: string
              password: string
  '/users/{authorId}/comments':
    get:
      summary: user Service Get Comments
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        authorId:
                          type: integer
                        postId:
                          type: integer
                        body:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - authorId
                        - postId
                        - body
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - comments
                  - total
                  - skip
                  - limit
              example:
                comments:
                  - id: 3213
                    authorId: 7416
                    postId: 7536
                    body: string
                  - id: 5929
                    authorId: 5363
                    postId: 8014
                    body: str
                total: 8709
                skip: 5940
                limit: 30
      tags:
        - users
        - '{authorId}'
        - comments
    parameters:
      - name: authorId
        in: path
        required: true
        schema:
          type: string
        example: string
  '/users/{authorId}/posts':
    get:
      summary: user Service Get Posts
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 30
          example: 30
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        authorId:
                          type: integer
                        title:
                          type: string
                          minLength: 1
                        body:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - authorId
                        - title
                        - body
                  total:
                    type: integer
                  skip:
                    type: integer
                  limit:
                    type: integer
                required:
                  - posts
                  - total
                  - skip
                  - limit
              example:
                posts:
                  - id: 900
                    authorId: 57
                    title: string
                    body: string
                  - id: 7337
                    authorId: 6165
                    title: string
                    body: string
                total: 558
                skip: 9145
                limit: 30
      tags:
        - users
        - '{authorId}'
        - posts
    parameters:
      - name: authorId
        in: path
        required: true
        schema:
          type: string
        example: string
  '/users/{id}':
    get:
      summary: user Service Get
      parameters:
        - name: select
          in: query
          required: false
          schema:
            type: string
          example: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                    minLength: 1
                  firstName:
                    type: string
                    minLength: 1
                  lastName:
                    type: string
                    minLength: 1
                required:
                  - id
                  - email
                  - firstName
                  - lastName
              example:
                id: 2611
                email: string
                firstName: string
                lastName: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - users
        - '{id}'
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: string
    patch:
      summary: user Service Update
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                    minLength: 1
                  firstName:
                    type: string
                    minLength: 1
                  lastName:
                    type: string
                    minLength: 1
                required:
                  - id
                  - email
                  - firstName
                  - lastName
              example:
                id: 2611
                email: string
                firstName: string
                lastName: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - users
        - '{id}'
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
            example:
              email: string
              firstName: string
              lastName: string
    delete:
      summary: user Service Delete
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful.'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - users
        - '{id}'
      security:
        - BearerAuth: []
  /:
    get:
      summary: New Request
      responses: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    BasicAuth:
      type: http
      scheme: basic
